# Generated by Django 4.2.10 on 2024-05-05 03:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paste",
            name="type",
            field=models.CharField(default="public", max_length=10),
        ),
        migrations.AddField(
            model_name="paste",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paste",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 6, 3, 55, 15, 324543, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
