# Generated by Django 4.2.10 on 2024-05-10 03:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_paste_expiration_date_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.FileField(
                upload_to="shared/",
                validators=[django.core.validators.MaxLengthValidator(20971520)],
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 10, 9, 46, 4, 788600, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paste",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 11, 3, 46, 4, 678386, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
