# Generated by Django 4.2.10 on 2024-05-10 04:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_file_content_alter_file_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.FileField(
                upload_to="shared/",
                validators=[django.core.validators.MaxLengthValidator(20971520)],
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 10, 10, 44, 29, 286699, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paste",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 11, 4, 44, 29, 161273, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
